name: Node.js CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        version: 10
    - name: npm install and test
      run: |
        npm install
        npm test
    - name: npm publish on NPM
      run: npm publish
      if: startsWith(github.event.ref, 'refs/tags')
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
