name: Node.js CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-node@v1
      with:
        version: '10.x'
        registry-url: 'https://registry.npmjs.org'
    - name: npm install, and test
      run: | 
        npm install
        npm test
    - run: npm publish on NPM
      if: github.event == 'release'
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
    - uses: actions/setup-node@v1
      if: github.event == 'release'
      with:
        registry-url: 'https://npm.pkg.github.com'
    - run: npm publish on GitHub
      if: github.event == 'release'
      env:
        NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
